##控制台打印sql日志方法一,打印的比较详细
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
  ##非注解形式的配置
#  mapper-locations: classpath:mybatis/*.xml
#  config-location: classpath:mybatis-config.xml

##控制台打印sql日志方法二,打印的比较粗略
#logging:
#  level:
#    com.jarry.mapper: debug

