spring:
  profiles:
    #当前应用环境
    active: mybatis
#当一个数据源的情况
  datasource:
    url: jdbc:mysql://101.132.40.203:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  #未使用thymeleaf模版,视图文件必须在拦截之外，既放在static-locations配置信息指向的文件夹下,如果是jsp，必须放在webapp/WEB-INF下才能访问到
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp
    #表示所有的访问都经过静态资源路径
    static-path-pattern: /**
    #默认classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    #静态资源路径
    #resources:
      #static-locations:
  #使用模版
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/

server:
  port:  8083

#多数据源的情况
multiple:
  db01:
    jdbc-url: jdbc:mysql://101.132.40.203:3306/test1
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  db02:
      jdbc-url: jdbc:mysql://101.132.40.203:3306/test
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456


#设置各种属性的值
#顶节点不能用驼峰标识，必须全小写或者 - 分隔
myprop:
  myMap:
    myKey1:
      id: 11
      name: 12
      password: 13
      age: 14
    myKey2:
          id: 21
          name: 22
          password: 23
          age: 24
  myList:
      - list1
      - list2
  myListMap:
      - value1: 值1
        value2: 值2
  myArray: 1,2,3,4,5
